default: &default
  adapter: postgresql
  encoding: unicode
  #uncomment for docker-compose build
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: trade-up_development

test:
  <<: *default
  database: trade-up_test
