default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  # host: db

development:
  <<: *default
  database: trade-up_development

test:
  <<: *default
  database: trade-up_test

staging:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pool: 5
  database: <%= ENV['POSTGRESQL_DB'] %>
